sudo: required
dist: trusty
language: node_js
addons:
  chrome: stable
before_install:
  - cd web-ui
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
node_js:
  - 12
cache: npm
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
  - npm run build
  - npm run test
